MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: 'pretrain/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  UNCERTAINTY: 0.5
  POS: [ 0,1,2,3,4,5 ]
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TEST: "cityscapes_val"
INPUT:
  INPUT_SIZE_TEST: (1536, 768)
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 31250
  STOP_ITER: 20000
  BATCH_SIZE: 4

